Blog app - Add forms
egichuhis/my-rails-blog pull request #7
Opened 2023-12-09 15:55 UTC by egichuhis

Hello, please review this PR.

Changes:

- Add forms to my Blog app.
- Create a method called current_user in my ApplicationController to make current user data available to all controllers.
- It returns the first user from the database.
- Create forms to perform the following functions:
  - Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
  - Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
  - Allow Users to add likes to Posts.

2023-12-09 23:10 UTC, Efiamotu-1 requested changes
Hi @egichuhis, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-09 23:10 UTC, Efiamotu-1 commented on app/controllers/posts_controller.rb
- [ ] Your project is missing a few important requirements as shown in the image below. currently you do not have any implementattion of the `new` method which is crucial in creating a new post, please kindly add this method using the code snippet below 
![mis](https://github.com/egichuhis/my-rails-blog/assets/89055502/820e7a1c-b97f-4fa3-903d-0d626a9a6f3b)
- code snippet
```ruby
 def new
      @post = Post.new
    end
```

2023-12-09 23:10 UTC, Efiamotu-1 commented on app/controllers/comments_controller.rb
- [ ] Your project is missing a few important requirements as shown in the image below. currently you do not have any implementation of the `new` method which is crucial in creating a new comment, please kindly add this method using the code snippet below. 
![mis](https://github.com/egichuhis/my-rails-blog/assets/89055502/820e7a1c-b97f-4fa3-903d-0d626a9a6f3b)
- code snippet
```ruby
 def new
      @comment = Comment.new
    end
```

2023-12-09 23:10 UTC, Efiamotu-1 commented on config/routes.rb
> +      resources :comments, only: [:create]
- [ ] You are also missing the routes for creating a new post and new comment, please kindly add them, for guidance see the code snippet below :+1: 
- code snippet
```ruby
resources :posts, only: [:index, :show, :create, :new] do
      resources :likes, only: [:create, :index]
      resources :comments, only: [:create, :new]
end

2023-12-09 23:10 UTC, Efiamotu-1 commented on app/views/comments/_form.html.erb
- [ ] There are no views created by you to handle adding a new comment, there should be a `new.html.erb` file which handles this, please kindly add this to your project.

2023-12-09 23:10 UTC, Efiamotu-1 commented on app/views/posts/_form.html.erb
- [ ] There are no views created by you to handle adding a new post, there should be a `new.html.erb` file which handles this, please kindly add this to your project.

2023-12-09 23:10 UTC, Efiamotu-1 commented on Gemfile
- @egichuhis  whenever your project is run by anyone there are no users to test with however you can  fix this by creating users, posts and comments in the `seeds.rb` file in your project so as to assist anyone testing your work, whenever they run the command `rails db:seed`. To do this add the below code in your `seeds.rb` file so that whenever the code `rails db:seed` is  run in the  terminal it creates the below users and your app can be tested properly
- code snippet

```ruby
   first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
   second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
```

2023-12-10 11:50 UTC, egichuhis commented
The form for creating new post has been added and is working well. 

In my controllers, I am using action:

`def create`

To create new comments and posts

2023-12-11 07:29 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @egichuhis,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Since this is a new week and the project was not approved kindly create a new pull request without comments from the last week's reviewer(s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-12-11 08:11 UTC, merged