Blog app - integration specs for views and fix n+1 problems
egichuhis/my-rails-blog pull request #9
Opened 2023-12-13 09:35 UTC by egichuhis

Hello, please review this PR.

Changes:

1. Secure app from n+1 problems.

The N+1 problem was already solved when fetching all posts and their comments for a user.
Code snippet Posts controller:

![posts](https://github.com/egichuhis/my-rails-blog/assets/10649124/d92e23cf-6d59-452b-bc8f-f99289c0871d)

Logs snippet when fetching posts (includes comments)

![logs](https://github.com/egichuhis/my-rails-blog/assets/10649124/d2749fb3-54ed-4f7d-9865-95abd5f9f82e)

2. Write integration tests with Capybara gem.

2023-12-15 08:03 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @egichuhis and @Rifat8080,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Is @Nelofarzabi assigned to this team? I cannot see any commits from them. Kindly ensure all team members contribute to the project, and list all team members on the README. Kindly share a screenshot of your dashboard to clarify @Nelofarzabi is not part of the team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-12-15 08:35 UTC, egichuhis commented
Dear reviewer, kindly note that this collaboration team has only 2 members. One of our members left within the week. ![Screenshot_20231215-112657.jpg](https://github.com/egichuhis/my-rails-blog/assets/10649124/a3161274-4d1b-42fa-a811-f78b32b25509)

2023-12-15 11:10 UTC, skyv26 requested changes
## Hi @egichuhis and @Rifat8080, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjBkZWI1YTgxNDg4Y2QzMWU2MjkyNjQ2MmY1MmIzMjM4ZmI1MGU1OCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fDWHJAmgrCeIw/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implemented the features and fixed `N+1` problem ✅ 

## Required Changes ♻️

- [ ] Please make sure that your test cases are passing, because I checked that your test cases are passing except for the `User` index template. On the other hand, as I mentioned below in the `first` inline comment you missed the `implementation` of the test for the `post` show endpoint. Kindly take a look again and fix the problem,

### Results
![image](https://github.com/egichuhis/my-rails-blog/assets/66476329/a62fae9f-6935-4cbd-89d9-728d5e3c3123)

- [ ] It seems like you did great work and did a lot of research, I noticed that you are using the `type:: system` for your `controller` testing, which will open the `chromium` tab to automate the test of your application. Which is nice but make sure that your `tests` are also passing with `type::feature`. Please put your controller specs into a `dedicated` folder to organize everything in a well-structured manner.

![image](https://github.com/egichuhis/my-rails-blog/assets/66476329/c4a583ef-bd0b-44ac-b152-720576fbeacc)

- [x] Please add your `pair-programming` partner details under the `author` section, which not only gives the proper credit for the contribution but also shows how you are a good team player. 

![image](https://github.com/egichuhis/my-rails-blog/assets/66476329/08c18683-b395-41f2-aade-3165763fc761)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-15 11:10 UTC, skyv26 commented on spec/posts_show_spec.rb
- [x] Well done @egichuhis you and your coding partner did a good job, but it seems like one of you forgot to implement the `capybara` testing for the `post` show functionality. Kindly add the test cases for your `post` show and make sure that your tests are passing before asking for a review.

![image](https://github.com/egichuhis/my-rails-blog/assets/66476329/3f86d4f5-8ce7-49fb-a674-1777214038da)

2023-12-15 12:06 UTC, tugsem requested changes
## STATUS: REQUIRED CHANGES ♻️
Hello @egichuhis 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Highlights 🚀
✔️Good job on fixing the failing tests and adding tests for the post feature.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-15 12:06 UTC, tugsem commented on spec/requests/users_spec.rb
>        expect(response).to render_template(:index)
- [ ] Please fix this error to make all the test pass. 
![image](https://github.com/egichuhis/my-rails-blog/assets/91486791/dda684d9-43db-4a0f-b048-7d981fdc36a2)

2023-12-15 12:18 UTC, egichuhis commented on spec/requests/users_spec.rb
>        expect(response).to render_template(:index)
All tests are passing. I have fixed and tested several times

![tests_working](https://github.com/egichuhis/my-rails-blog/assets/10649124/d8eafe9f-83a1-4005-85e5-6289b3787676)

2023-12-15 13:59 UTC, souad988 requested changes
Hi @egichuhis  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Great efforts 
Good file structure
Communicate with reviewers using comments

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-15 13:59 UTC, souad988 commented on README.md
> +
well done by adding your collaborators to the readme 👍🏼

2023-12-15 13:59 UTC, souad988 commented on spec/requests/users_spec.rb
>        expect(response).to render_template(:index)
Good job @egichuhis the tests in the system folder are all running but still the first test in requests/user_spec file is failing please check your routes as it is triggering the index action in posts controller refer to the screenshot
![Screenshot from 2023-12-15 14-49-56](https://github.com/egichuhis/my-rails-blog/assets/59707859/10ffeca8-2745-4192-bdb8-788c943c92e8)

2023-12-16 08:45 UTC, egichuhis commented
![Screenshot from 2023-12-16 08-41-44](https://github.com/egichuhis/my-rails-blog/assets/10649124/a65ec47f-4adb-4ae9-bae7-8711a25725c7)

2023-12-16 09:18 UTC, mckent05 approved these changes
Hi @egichuhis,

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-16 09:28 UTC, merged